MATLAB_path = '/usr/local/bin/./matlab'
Result_dir='../result/'
Data_file='../data/covid_times_remove_ny_nj.csv'
Seg_file='../segment/covid_enacted_all_2week'
Result_file='covid_interventions'
demo:
	python3 expl_time_series.py $(Data_file) $(Seg_file) $(Result_file) $(Result_dir) $(MATLAB_path) true


